// SPDX-License-Identifier: AGPL-3.0-or-later
// Check-in protocol shared by the API, the web scanner and (Phase 4b) the offline queue.
import { z } from "zod";
import { eventStatuses } from "./events.ts";

/** Scanning opens this long before the event starts (maintainer decision, ADR-0009). */
export const CHECK_IN_OPENS_BEFORE_MS = 6 * 60 * 60 * 1000;
/** When an event has no end time, scanning closes this long after it starts. */
export const CHECK_IN_DEFAULT_DURATION_MS = 12 * 60 * 60 * 1000;

export function checkInWindow(event: { startsAt: Date; endsAt: Date | null }): {
  opensAt: Date;
  closesAt: Date;
} {
  return {
    opensAt: new Date(event.startsAt.getTime() - CHECK_IN_OPENS_BEFORE_MS),
    closesAt: event.endsAt ?? new Date(event.startsAt.getTime() + CHECK_IN_DEFAULT_DURATION_MS),
  };
}

export const checkInOutcomes = [
  "valid",
  "already_used",
  "invalid",
  "wrong_event",
  "revoked",
  "outside_window",
] as const;
export type CheckInOutcome = (typeof checkInOutcomes)[number];

export const checkInRequestSchema = z.discriminatedUnion("method", [
  z.object({
    method: z.literal("qr"),
    token: z.string().min(1).max(512),
    /** Generated by the device per scan; retries with the same id are idempotent. */
    clientCheckInId: z.uuid(),
    deviceId: z.string().max(64).optional(),
  }),
  z.object({
    method: z.literal("manual"),
    attendeeId: z.uuid(),
    clientCheckInId: z.uuid(),
    deviceId: z.string().max(64).optional(),
  }),
]);
export type CheckInRequest = z.infer<typeof checkInRequestSchema>;

export const checkInResultSchema = z.object({
  outcome: z.enum(checkInOutcomes),
  /** Present for valid and already_used results. */
  attendee: z.object({ id: z.uuid(), name: z.string() }).nullable(),
  /** First check-in time (valid: now; already_used: when it happened). */
  checkedInAt: z.iso.datetime({ offset: true }).nullable(),
  counts: z.object({ checkedIn: z.number().int(), registered: z.number().int() }),
});
export type CheckInResult = z.infer<typeof checkInResultSchema>;

export const scanContextSchema = z.object({
  event: z.object({
    id: z.uuid(),
    name: z.string(),
    startsAt: z.iso.datetime({ offset: true }),
    timezone: z.string(),
    venueName: z.string(),
    status: z.enum(eventStatuses),
  }),
  window: z.object({
    opensAt: z.iso.datetime({ offset: true }),
    closesAt: z.iso.datetime({ offset: true }),
  }),
  role: z.enum(["organizer", "staff"]),
  counts: z.object({ checkedIn: z.number().int(), registered: z.number().int() }),
});
export type ScanContext = z.infer<typeof scanContextSchema>;

export const scanSearchQuerySchema = z.object({ q: z.string().trim().min(2).max(100) });

export const scanSearchResultSchema = z.array(
  z.object({
    id: z.uuid(),
    name: z.string(),
    /** Partial email so staff can tell people apart without seeing full addresses. */
    maskedEmail: z.string(),
    checkedInAt: z.iso.datetime({ offset: true }).nullable(),
  }),
);
export type ScanSearchResult = z.infer<typeof scanSearchResultSchema>;

/** `ana.lopez@gmail.com` → `an***@gmail.com`. */
export function maskEmail(email: string): string {
  const at = email.lastIndexOf("@");
  if (at <= 0) return "***";
  const local = email.slice(0, at);
  return `${local.slice(0, Math.min(2, local.length - 1) || 1)}***${email.slice(at)}`;
}

export const eventStatsSchema = z.object({
  registered: z.number().int(),
  checkedIn: z.number().int(),
  /** Registered but not checked in; final once the event is over. */
  notCheckedIn: z.number().int(),
  pendingInvitations: z.number().int(),
  /** Scans of tickets that were already used (possible sharing of a QR). */
  repeatedScans: z.number().int(),
  rejectedScans: z.number().int(),
  recent: z.array(
    z.object({
      attendeeId: z.uuid(),
      name: z.string(),
      checkedInAt: z.iso.datetime({ offset: true }),
      method: z.enum(["qr", "manual"]),
      scannedBy: z.string().nullable(),
    }),
  ),
});
export type EventStats = z.infer<typeof eventStatsSchema>;
