// SPDX-License-Identifier: AGPL-3.0-or-later
import { z } from "zod";
import { emailSchema, personNameSchema } from "./auth.ts";
import { localeSchema } from "./locale.ts";
import { isValidTimeZone } from "./timezone.ts";

export const EVENT_NAME_MAX = 120;
export const EVENT_DESCRIPTION_MAX = 5_000;
export const MAX_REGISTRATION_FIELDS = 10;
export const MAX_SELECT_OPTIONS = 20;
export const TEXT_ANSWER_MAX = 500;

export const eventStatuses = ["draft", "published", "closed"] as const;
export type EventStatus = (typeof eventStatuses)[number];
export const registrationModes = ["open", "closed"] as const;
export type RegistrationMode = (typeof registrationModes)[number];

export const timeZoneSchema = z
  .string()
  .min(1)
  .max(64)
  .refine(isValidTimeZone, { message: "Unknown time zone" });

const instantSchema = z.iso.datetime({ offset: true });

/** Field keys are generated by the client (`f1`, `f2`, ...) and stay stable across edits. */
const fieldKeySchema = z.string().regex(/^[a-z][a-z0-9_]{0,31}$/);
const fieldLabelSchema = z.string().trim().min(1).max(100);

export const registrationFieldSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("text"),
    key: fieldKeySchema,
    label: fieldLabelSchema,
    required: z.boolean(),
  }),
  z.object({
    type: z.literal("select"),
    key: fieldKeySchema,
    label: fieldLabelSchema,
    required: z.boolean(),
    options: z.array(z.string().trim().min(1).max(100)).min(1).max(MAX_SELECT_OPTIONS),
  }),
  z.object({
    type: z.literal("checkbox"),
    key: fieldKeySchema,
    label: fieldLabelSchema,
    required: z.boolean(),
  }),
]);
export type RegistrationField = z.infer<typeof registrationFieldSchema>;

export const registrationFieldsSchema = z
  .array(registrationFieldSchema)
  .max(MAX_REGISTRATION_FIELDS)
  .refine((fields) => new Set(fields.map((f) => f.key)).size === fields.length, {
    message: "Field keys must be unique",
  });

const eventFields = {
  name: z.string().trim().min(1).max(EVENT_NAME_MAX),
  description: z.string().trim().max(EVENT_DESCRIPTION_MAX).nullable(),
  startsAt: instantSchema,
  endsAt: instantSchema.nullable(),
  timezone: timeZoneSchema,
  venueName: z.string().trim().min(1).max(200),
  venueAddress: z.string().trim().max(500).nullable(),
  capacity: z.number().int().min(1).max(100_000).nullable(),
  registrationMode: z.enum(registrationModes),
  registrationDeadline: instantSchema.nullable(),
  registrationFields: registrationFieldsSchema,
};

export interface DateIssue {
  path: ["endsAt"] | ["registrationDeadline"];
  message: string;
}

/** Cross-field date rules, shared by create (schema) and update (merged event in the API). */
export function eventDateIssues(event: {
  startsAt: string;
  endsAt: string | null;
  registrationDeadline: string | null;
}): DateIssue[] {
  const issues: DateIssue[] = [];
  if (event.endsAt && Date.parse(event.endsAt) <= Date.parse(event.startsAt)) {
    issues.push({ path: ["endsAt"], message: "endsAt must be after startsAt" });
  }
  const end = event.endsAt ?? event.startsAt;
  if (event.registrationDeadline && Date.parse(event.registrationDeadline) > Date.parse(end)) {
    issues.push({
      path: ["registrationDeadline"],
      message: "registrationDeadline must not be after the event ends",
    });
  }
  return issues;
}

export const eventInputSchema = z.object(eventFields).superRefine((event, ctx) => {
  for (const issue of eventDateIssues(event)) ctx.addIssue({ code: "custom", ...issue });
});
export type EventInput = z.infer<typeof eventInputSchema>;

/** PATCH body: any subset of fields. Cross-field rules are re-checked on the merged event. */
export const eventUpdateSchema = z.object(eventFields).partial();
export type EventUpdate = z.infer<typeof eventUpdateSchema>;

export const eventSchema = z.object({
  id: z.uuid(),
  organizationId: z.uuid(),
  slug: z.string(),
  ...eventFields,
  status: z.enum(eventStatuses),
  registeredCount: z.number().int(),
  createdAt: instantSchema,
  updatedAt: instantSchema,
});
export type Event = z.infer<typeof eventSchema>;

/** Why a public registration form is not accepting submissions right now. */
export const registrationStates = [
  "open",
  "invitation_only",
  "deadline_passed",
  "full",
  "closed",
] as const;
export type RegistrationState = (typeof registrationStates)[number];

export const publicEventSchema = z.object({
  slug: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  startsAt: instantSchema,
  endsAt: instantSchema.nullable(),
  timezone: z.string(),
  venueName: z.string(),
  venueAddress: z.string().nullable(),
  organizerName: z.string(),
  registrationState: z.enum(registrationStates),
  registrationDeadline: instantSchema.nullable(),
  registrationFields: registrationFieldsSchema,
});
export type PublicEvent = z.infer<typeof publicEventSchema>;

export const answerValueSchema = z.union([z.string().max(TEXT_ANSWER_MAX), z.boolean()]);
export type Answers = Record<string, string | boolean>;

export const registrationInputSchema = z.object({
  name: personNameSchema,
  email: emailSchema,
  locale: localeSchema,
  answers: z.record(fieldKeySchema, answerValueSchema).default({}),
});
export type RegistrationInput = z.infer<typeof registrationInputSchema>;

export type AnswerIssue = { key: string; problem: "required" | "invalid" | "unknown" };

/** Validates answers against the event's field definitions and returns the normalized answers. */
export function validateAnswers(
  fields: readonly RegistrationField[],
  answers: Record<string, unknown>,
): { ok: true; answers: Answers } | { ok: false; issues: AnswerIssue[] } {
  const issues: AnswerIssue[] = [];
  const out: Answers = {};
  const known = new Set(fields.map((f) => f.key));
  for (const key of Object.keys(answers)) {
    if (!known.has(key)) issues.push({ key, problem: "unknown" });
  }
  for (const field of fields) {
    const value = answers[field.key];
    if (field.type === "checkbox") {
      if (value !== undefined && typeof value !== "boolean")
        issues.push({ key: field.key, problem: "invalid" });
      else if (field.required && value !== true)
        issues.push({ key: field.key, problem: "required" });
      else out[field.key] = value === true;
      continue;
    }
    const text = typeof value === "string" ? value.trim() : value;
    if (text === undefined || text === "") {
      if (field.required) issues.push({ key: field.key, problem: "required" });
      continue;
    }
    if (typeof text !== "string" || text.length > TEXT_ANSWER_MAX) {
      issues.push({ key: field.key, problem: "invalid" });
    } else if (field.type === "select" && !field.options.includes(text)) {
      issues.push({ key: field.key, problem: "invalid" });
    } else {
      out[field.key] = text;
    }
  }
  return issues.length > 0 ? { ok: false, issues } : { ok: true, answers: out };
}

export const attendeeStatuses = ["active", "cancelled"] as const;
export const attendeeSources = ["open_registration", "import", "manual"] as const;
export const ticketStatuses = ["active", "superseded", "revoked"] as const;
export type TicketStatus = (typeof ticketStatuses)[number];

export const attendeeSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
  status: z.enum(attendeeStatuses),
  source: z.enum(attendeeSources),
  answers: z.record(z.string(), answerValueSchema),
  ticketStatus: z.enum(ticketStatuses).nullable(),
  createdAt: instantSchema,
});
export type Attendee = z.infer<typeof attendeeSchema>;

/** What the attendee sees on their "my ticket" page. */
export const ticketViewSchema = z.object({
  attendee: z.object({ name: z.string(), status: z.enum(attendeeStatuses) }),
  event: publicEventSchema.pick({
    slug: true,
    name: true,
    startsAt: true,
    endsAt: true,
    timezone: true,
    venueName: true,
    venueAddress: true,
    organizerName: true,
  }),
  ticket: z.object({
    status: z.enum(ticketStatuses),
    /** Present only while the ticket is valid. */
    qrToken: z.string().nullable(),
  }),
});
export type TicketView = z.infer<typeof ticketViewSchema>;

export const registrationResultSchema = z.object({ status: z.literal("registered") });
