/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database connectivity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API and database are healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @enum {string} */
                            database: "ok" | "unavailable";
                            version: string;
                        };
                    };
                };
                /** @description Database is unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @enum {string} */
                            database: "ok" | "unavailable";
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events of the active organization */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a draft event (generates its first signing key) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description: string | null;
                        /** Format: date-time */
                        startsAt: string;
                        /** Format: date-time */
                        endsAt: string | null;
                        timezone: string;
                        venueName: string;
                        venueAddress: string | null;
                        capacity: number | null;
                        /** @enum {string} */
                        registrationMode: "open" | "closed";
                        /** Format: date-time */
                        registrationDeadline: string | null;
                        registrationFields: ({
                            /** @enum {string} */
                            type: "text";
                            key: string;
                            label: string;
                            required: boolean;
                        } | {
                            /** @enum {string} */
                            type: "select";
                            key: string;
                            label: string;
                            required: boolean;
                            options: string[];
                        } | {
                            /** @enum {string} */
                            type: "checkbox";
                            key: string;
                            label: string;
                            required: boolean;
                        })[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a draft event */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Edit an event (allowed in any status) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string | null;
                        /** Format: date-time */
                        startsAt?: string;
                        /** Format: date-time */
                        endsAt?: string | null;
                        timezone?: string;
                        venueName?: string;
                        venueAddress?: string | null;
                        capacity?: number | null;
                        /** @enum {string} */
                        registrationMode?: "open" | "closed";
                        /** Format: date-time */
                        registrationDeadline?: string | null;
                        registrationFields?: ({
                            /** @enum {string} */
                            type: "text";
                            key: string;
                            label: string;
                            required: boolean;
                        } | {
                            /** @enum {string} */
                            type: "select";
                            key: string;
                            label: string;
                            required: boolean;
                            options: string[];
                        } | {
                            /** @enum {string} */
                            type: "checkbox";
                            key: string;
                            label: string;
                            required: boolean;
                        })[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/events/{eventId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            organizationId: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            capacity: number | null;
                            /** @enum {string} */
                            registrationMode: "open" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                            /** @enum {string} */
                            status: "draft" | "published" | "closed";
                            registeredCount: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/signing-keys/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the event signing key; existing tickets stay valid */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New active key version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/attendees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attendees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            status: "active" | "cancelled";
                            /** @enum {string} */
                            source: "open_registration" | "import" | "manual";
                            answers: {
                                [key: string]: string | boolean;
                            };
                            /** @enum {string|null} */
                            ticketStatus: "active" | "superseded" | "revoked" | null;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendees/{attendeeId}/ticket/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new QR and link, emailed to the attendee */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attendeeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendees/{attendeeId}/ticket/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the attendee's current QR */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attendeeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendees/{attendeeId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel the registration and revoke its ticket */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attendeeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public event page data (published and closed events only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            slug: string;
                            name: string;
                            description: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** Format: date-time */
                            endsAt: string | null;
                            timezone: string;
                            venueName: string;
                            venueAddress: string | null;
                            organizerName: string;
                            /** @enum {string} */
                            registrationState: "open" | "invitation_only" | "deadline_passed" | "full" | "closed";
                            /** Format: date-time */
                            registrationDeadline: string | null;
                            registrationFields: ({
                                /** @enum {string} */
                                type: "text";
                                key: string;
                                label: string;
                                required: boolean;
                            } | {
                                /** @enum {string} */
                                type: "select";
                                key: string;
                                label: string;
                                required: boolean;
                                options: string[];
                            } | {
                                /** @enum {string} */
                                type: "checkbox";
                                key: string;
                                label: string;
                                required: boolean;
                            })[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{slug}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open registration; the ticket is emailed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        email: string;
                        /** @enum {string} */
                        locale: "es-MX" | "en";
                        /** @default {} */
                        answers?: {
                            [key: string]: string | boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "registered";
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Conflicts with the current state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tickets/{accessToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The attendee's ticket, reached through the secret link */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accessToken: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            attendee: {
                                name: string;
                                /** @enum {string} */
                                status: "active" | "cancelled";
                            };
                            event: {
                                slug: string;
                                name: string;
                                /** Format: date-time */
                                startsAt: string;
                                /** Format: date-time */
                                endsAt: string | null;
                                timezone: string;
                                venueName: string;
                                venueAddress: string | null;
                                organizerName: string;
                            };
                            ticket: {
                                /** @enum {string} */
                                status: "active" | "superseded" | "revoked";
                                qrToken: string | null;
                            };
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tickets/{accessToken}/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** QR code image of a valid ticket */
        get: {
            parameters: {
                query?: {
                    download?: "1";
                };
                header?: never;
                path: {
                    accessToken: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PNG image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tickets/{accessToken}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The attendee cancels their own registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accessToken: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            type: string;
                            title: string;
                            status: number;
                            /** @enum {string} */
                            code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "invalid_origin" | "internal_error" | "invalid_state" | "registration_closed" | "event_full" | "already_registered";
                            detail?: string;
                            instance?: string;
                            requestId?: string;
                            issues?: {
                                path: (string | number)[];
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
